// WebUI/src/Vue/viewshare.vue
<template>
    <modal name="AddShareModal" :min-width="600" :min-height="240" :adaptive="true" :draggable="draggable" :resizable="true" height="240" transition="nice-modal-fade" classes="myclasses" @before-open="beforeOpen" @before-close="beforeClose">
        <div class="modalheader"><label>Add a new Share</label></div>
        <div class="modalcontainer">
            <div class="header">
                <form>
                    <table>
                        <tr>
                            <td>Unique Name :</td>
                            <td><input type="text" v-model="share.Name" required placeholder="e.g. mydocs"></td>
                        </tr>
                        <tr>
                            <td>Local Path :</td>
                            <td><input type="text" v-model="share.Path" required placeholder="e.g. C:\My Documents"></td>
                        </tr>
                        <tr>
                            <td>Read Only Token :</td>
                            <td><input type="text" readonly v-model="share.ReadOnlyToken"></td>
                        </tr>
                        <tr>
                            <td>Read Write Token :</td>
                            <td><input type="text" readonly v-model="share.ReadWriteToken"></td>
                        </tr>
                    </table>
                </form>
            </div>
            <div class="buttonbar">
                <button v-if="isnew===true" class="actionbutton" @click="save">Save</button>
                <button class="actionbutton" @click="close" style="float: right;">Close</button>
            </div>
            <div class="vue-modal-resizer"></div>
        </div>
        </div>
    </modal>
</template>

<script>
    export default {
        name: 'AddShareModal',
        props: ["share", "draggable"],
        data() {
            return {
                allowclose: false,
                isnew: true
            }
        },
        methods: {
            save() {
                var ok = true;
                if (this.share.Name === '') ok = false;
                if (this.share.Path === '') ok = false;
                if (ok === false) {
                    swal('Please enter values');
                    return;
                }
                var that = this;
                $.post2("api/share.add", this.share, function(data) {
                    that.allowclose = true;
                    that.$modal.hide('AddShareModal');
                    that.$emit("refresh");
                });
            },
            close() {
                this.allowclose = true;
                this.$modal.hide('AddShareModal');
            },
            beforeOpen(event) {
                this.allowclose = false;
            },
            beforeClose(event) {
                if (this.allowclose === false)
                    event.stop();
                else {
                    this.allowclose = false;
                }
            }
        },
        watch: {
            share() {
                this.isnew = true;
                if (this.share.Name !== "")
                    this.isnew = false;
            }
        },
        mounted() {
            this.allowclose = false;
        }
    }
</script>

<style>
    .modalheader {
        background: darkgrey;
        padding: 5px;
        text-align: center;
        margin: -10px;
        margin-bottom: 5px;
    }
    .modalcontainer {}
    .myclasses {
        border-radius: 20px;
        border: solid 2px #444444;
        padding: 10px;
        background: white;
        box-shadow: 0 2px 30px rgba(0, 0, 0, 1);
    }
    .v--modal-overlay[data-modal="AddShareModal"] {
        background: rgba(0, 0, 0, 0.5);
    }
    .buttonbar {
        position: absolute;
        width: 95%;
        bottom: 0;
    }
    .vue-modal-resizer {
        display: block;
        overflow: hidden;
        position: absolute;
        width: 12px;
        height: 12px;
        right: 0;
        bottom: 0;
        z-index: 9999999;
        background: red;
        cursor: se-resize;
    }
</style>

// WebUINew/src/pages/viewshare.svelte
<script>
  import { createEventDispatcher } from "svelte";
  import Modal from "../UI/Modal.svelte";
  import Button from "../UI/button.svelte";
  import msgbox from "../UI/msgbox.js";
  

  export let share ;//= new Share();
  export let isnew = true;
  export let show = true;
  export let node;

  const dispatch = createEventDispatcher();

  function save() {
    var ok = true;
    if (share.Name === "") ok = false;
    if (share.Path === "") ok = false;
    if (ok === false) {
      msgbox.Ok("Please enter values", "Incomplete");
      return;
    }
    window.POST("api/share.add", share, function(data) {
      close();
    });
  }

  function close() {
    show = false;
    setTimeout(() => {
      document.body.removeChild(node);
    }, 1000);
    dispatch("close");
  }

  // share() {
  //     this.isnew = true;
  //     if (this.share.Name !== "")
  //         this.isnew = false;
  // }
</script>

<style>

</style>

<svelte:options accessors={true} />

<Modal minwidth="600" minheight="300" title="Add a new Share" {show}>
  <div slot="content">
    <div class="header">
      <form>
        <table>
          <tr>
            <td>Unique Name :</td>
            <td>
              <input
                type="text"
                bind:value={share.Name}
                required
                placeholder="e.g. mydocs" />
            </td>
          </tr>
          <tr>
            <td>Local Path :</td>
            <td>
              <input
                type="text"
                bind:value={share.Path}
                required
                placeholder="e.g. C:\My Documents" />
            </td>
          </tr>
          <tr>
            <td>Read Only Token :</td>
            <td>
              <input type="text" readonly bind:value={share.ReadOnlyToken} />
            </td>
          </tr>
          <tr>
            <td>Read Write Token :</td>
            <td>
              <input type="text" readonly bind:value={share.ReadWriteToken} />
            </td>
          </tr>
        </table>
      </form>
    </div>
  </div>
  <footer slot="footer">
    {#if isnew}
      <Button on:click={save}>Connect</Button>
    {/if}
    <Button on:click={close}>Close</Button>
  </footer>
</Modal>
