// WebUINew/src/pages/connection.svelte
<script>
  import { onMount } from "svelte";
  import msgbox from "../UI/msgbox.js";
  import Button from "../UI/button.svelte";
  import ConnectTo from "./connectto.svelte";
  import ConnectInfo from "./connview.svelte";
  import Fa from "svelte-fa";
  import icons from "../icons.js";
  //   import DataTable from "../UI/datatable.svelte";

  export let active = false;

  let connections = [];
  let findconn = "";
  let selected;
  let sortcol = "Name";
  let sortAsc = true;

  let connfilter = [];

  $: connfilter = window.FILTER(connections, findconn, sortcol, sortAsc);
  $: if (active) refresh();

  onMount(() => {
    refresh();
  });

  function remove(conn) {
    msgbox.OkCancel(
      "Do you want to remove this connection?",
      "Remove?",
      inputValue => {
        if (inputValue !== "") {
          window.GET(
            "api/connection.remove?" + conn.MachineName + "&" + conn.Name,
            function() {
              refresh();
            }
          );
        }
      }
    );
  }

  function sorticon(name, sc, sa) {
    if (sc === name) {
      if (sa === true) return icons.faSortAlphaDown;
      return icons.faSortAlphaDownAlt;
    }
    return "";
  }

  function pause(conn) {
    // console.log(conn);
    window.GET(
      "api/connection.pauseresume?" +
        conn.MachineName +
        "&" +
        conn.Name +
        "&true",
      function() {
        refresh();
      }
    );
  }
  function resume(conn) {
    var that = this;
    window.GET(
      "api/connection.pauseresume?" +
        conn.MachineName +
        "&" +
        conn.Name +
        "&false",
      function() {
        refresh();
      }
    );
  }
  function view(conn, isnew) {
    var n = document.createElement("div");
    var e = document.body.appendChild(n);
    var ct = new ConnectInfo({
      target: n,
      props: { node: n, connection: conn }
    });
    ct.show = true;
    ct.$on("close", e => refresh());
  }

  function confirm(conn) {
    msgbox.OkCancel(
      "Do you want to confirm this connection",
      "Confirm?",
      inputValue => {
        if (inputValue !== "") {
          //machinename & share & bool
          window.GET(
            "api/connection.confirm?" +
              conn.MachineName +
              "&" +
              conn.Name +
              "&true",
            function() {
              refresh();
            }
          );
        }
      }
    );
  }

  function sort(col) {
    if (col !== sortcol) {
      sortAsc = true;
      sortcol = col;
    } else sortAsc = !sortAsc;
  }

  function refresh() {
    window.GET("api/getconnections", function(data) {
      data.forEach((o, i) => (o.id = i));
      connections = data;
      // console.log( connections);
    });
  }

  function connectto() {
    var n = document.createElement("div");
    var e = document.body.appendChild(n);
    var ct = new ConnectTo({
      target: n,
      props: { node: n, id: "", path: "" }
    });
    ct.show = true;
    ct.$on("close", e => refresh());
  }
</script>

<style>
  .al {
    text-decoration: underline;
    cursor: pointer;
    margin-right: 8px;
  }
</style>

<svelte:options accessors={true} />

{#if active}
  <div class="tab-content">
    <h2>
      <Fa icon={icons.faExchangeAlt} />
      Connections to other machines
    </h2>
    <Button on:click={connectto}>
      <Fa icon={icons.faExchangeAlt} />
      Connect To
    </Button>
    {#if connections.length > 0}
      <span>
        <label>
          <Fa icon={icons.faFilter} />
          Filter :
        </label>
        <input
          type="text"
          bind:value={findconn}
          placeholder="Type here to filter the grid" />
        <button on:click={() => (findconn = '')}>X</button>
        <label style="margin-left:5px;">Count = {connfilter.length}</label>
      </span>
      <div class="cssTbl">
        <table>
          <tr>
            <th on:click={() => sort('Name')}>
              <label>
                Share
                <Fa icon={sorticon('Name', sortcol, sortAsc)} />
              </label>
            </th>
            <th on:click={() => sort('MachineName')}>
              <label>
                Machine
                <Fa icon={sorticon('MachineName', sortcol, sortAsc)} />
              </label>
            </th>
            <th>
              <label on:click={() => sort('Path')}>
                Local Path
                <Fa icon={sorticon('Path', sortcol, sortAsc)} />
              </label>
            </th>
            <th>
              <label on:click={() => sort('isClient')}>
                Type
                <Fa icon={sorticon('isClient', sortcol, sortAsc)} />
              </label>
            </th>
            <th>
              <label on:click={() => sort('isPaused')}>
                Status
                <Fa icon={sorticon('isPaused', sortcol, sortAsc)} />
              </label>
            </th>
            <th>
              <label>Actions</label>
            </th>
          </tr>
          {#each connfilter as s (s.id)}
            <tr>
              <td>
                <label>
                  <label on:click={() => view(s, false)}>{s.Name}</label>
                </label>
              </td>
              <td>
                <label>{s.MachineName}</label>
              </td>
              <td>
                <label>{s.Path}</label>
              </td>
              <td>
                <label>
                  {s.isClient ? 'Client' : 'Server'} {s.ReadOnly ? 'RO' : 'RW'}
                </label>
              </td>
              <td>
                <Fa
                  icon={s.isPaused ? icons.faPause : icons.faPlay}
                  color={s.isPaused ? 'red' : 'green'} />
                <label style={s.isPaused ? 'color:red;' : 'color:green;'}>
                  {s.isPaused ? 'Paused' : 'Running'}
                </label>
              </td>
              <td>
                {#if s.isPaused === false}
                  <label class="al" on:click={() => pause(s)}>
                    <Fa icon={icons.faPause} />
                    Pause
                  </label>
                {:else}
                  <label class="al" on:click={() => resume(s)}>
                    <Fa icon={icons.faPlay} />
                    Resume
                  </label>
                {/if}
                <label class="al" on:click={() => remove(s)}>
                  <Fa icon={icons.faTimes} />
                  Disconnect
                </label>
                {#if s.isConfirmed === false}
                  {#if s.isClient === false}
                    <label class="al" on:click={() => confirm(s)}>
                      <span class="gi gi-ok" />
                      Confirm
                    </label>
                  {:else}
                    <label v-else>Waiting for Confirm</label>
                  {/if}
                {/if}
              </td>
            </tr>
          {/each}
        </table>
      </div>
    {/if}

    <!-- <DataTable
      rows={connfilter}
      action={['name', 'token']}
      mapping={{"Name":"Share", "Path": "Local Path", "MachineName": "Machine"}}
      hide={['isConfirmed', 'ReadOnly', 'isPaused', 'isClient']}
      on:action={ae}>
    </DataTable> -->
  </div>
{/if}

// WebUI/src/Vue/connection.vue
<template>
    <div>
        <button class="actionbutton" @click="connectto"><span class="gi gi-transfer" style="margin-right:10px;"></span>Connect To</button>
        <span v-if="connfilter.length>0">
            <label><span class="gi gi-filter"></span>Filter :</label>
            <input type="text" v-model="findconn" placeholder="Type here to filter the grid">
            <button @click="findconn=''">X</button>
            <label style="margin-left:5px;">Count = {{connfilter.length}}</label>
        </span>
        <div class="cssTbl">
            <table v-if="connfilter.length>0">
                <tr>
                    <th><a @click="sort('Name')">Share<span :class="sorticon('Name')"></span></a></th>
                    <th><a @click="sort('MachineName')">Machine<span :class="sorticon('MachineName')"></span></a></th>
                    <th><a @click="sort('Path')">Local Path<span :class="sorticon('Path')"></span></a></th>
                    <th><a @click="sort('isClient')">Type<span :class="sorticon('isClient')"></span></a></th>
                    <th><a @click="sort('isPaused')">Status<span :class="sorticon('isPaused')"></span></a></th>
                    <th><a>Actions</a></th>
                </tr>
                <tr v-for="(s,i) in connfilter">
                    <td><label><a @click="view(s)">{{s.Name}}</a></label></td>
                    <td>
                        <label>{{s.MachineName}}</label>
                    </td>
                    <td>
                        <label>{{s.Path}}</label>
                    </td>
                    <td>
                        <label>{{s.isClient?'Client':'Server'}} {{s.ReadOnly?'RO':'RW'}}</label>
                    </td>
                    <td>
                        <span :class="s.isPaused?'gi gi-pause':'gi gi-play'" :style="s.isPaused?'color:red;':'color:green;'"></span>
                        <label :style="s.isPaused?'color:red;':'color:green;'">{{ s.isPaused ? "Paused":"Running"}}</label>
                    </td>
                    <td>
                        <label><a class="al" @click="pause(s)"><span class="gi gi-pause"></span>Pause</a></label>
                        <label><a class="al" @click="resume(s)"><span class="gi gi-play"></span>Resume</a></label>
                        <label><a class="al" @click="remove(s)"><span class="gi gi-remove"></span>Disconnect</a></label>
                        <label v-if="s.isConfirmed===false">
                            <a v-if="s.isClient===false" class="al" @click="confirm(s)"><span class="gi gi-ok"></span>Confirm</a>
                            <a v-else>Waiting for Confirm</a>
                        </label>
                    </td>
                </tr>
            </table>
        </div>
        <connview :connection="selected" :draggable="draggable"></connview>
        <connectto @refresh="refresh" :draggable="draggable"></connectto>
    </div>
</template>

<script>
    import connview from './connview.vue'
    import connto from './connectto.vue'
    export default {
        data() {
            return {
                findconn: '',
                selected : {},
                sortcol: 'Name',
                sortAsc: true
            }
        },
        components: {
            "connview": connview,
            "connectto": connto
        },
        props: ['connections'],
        methods: {
            remove(conn) {
                var that = this;
                swal({
                    title: "Remove?",
                    text: "Do you want to remove this connection?",
                    showCancelButton: true,
                    closeOnConfirm: true,
                    cancelButtonText: 'Cancel',
                    animation: "slide-from-top"
                }, function(inputValue) {
                    if (inputValue === false) return false;
                    if (inputValue !== "") {
                        $.get2("api/connection.remove?" + conn.MachineName + "&" + conn.Name, function() {
                            that.$emit("refresh");
                        });
                    }
                });
            },
            sorticon(name) {
                if (this.sortcol === name) {
                    if (this.sortAsc === true)
                        return 's gi gi-sort-by-alphabet';
                    return 's gi gi-sort-by-alphabet-alt';
                }
                return '';
            },
            pause(conn) {
                var that = this;
                $.get2("api/connection.pauseresume?" + conn.MachineName + "&" + conn.Name + "&true", function() {
                    that.$emit("refresh");
                });
            },
            resume(conn) {
                var that = this;
                $.get2("api/connection.pauseresume?" + conn.MachineName + "&" + conn.Name + "&false", function() {
                    that.$emit("refresh");
                });
            },
            view(conn) {
                this.selected = conn;
                this.$modal.show("ConnModal");
            },
            confirm(conn) {
                var that = this;
                swal({
                    title: "Confirm?",
                    text: "Do you want to confirm this connection",
                    showCancelButton: true,
                    closeOnConfirm: true,
                    cancelButtonText: 'Cancel',
                    animation: "slide-from-top"
                }, function(inputValue) {
                    if (inputValue === false) return false;
                    if (inputValue !== "") {
                        //machinename & share & bool
                        $.get2("api/connection.confirm?" + conn.MachineName + "&" + conn.Name + "&true", function() {
                            that.$emit("refresh");
                        });
                    }
                });
            },
            sort(col) {
                if (col !== this.sortcol) {
                    this.sortAsc = true;
                    this.sortcol = col;
                } else
                    this.sortAsc = !this.sortAsc;
            },
            refresh() {
                this.$emit("refresh");
            },
            connectto() {
                this.$modal.show("ConnectToModal");
            }
        },
        computed: {
            connfilter() {
                return $.filter(this.connections, this.findconn, this.sortcol, this.sortAsc);
            },
            draggable(){
                return window.draggable;
            }
        }
    }
</script>

<style scoped>
    .al {
        text-decoration: underline;
        cursor: pointer;
        margin-right: 8px;
    }
    .s {
        margin-left: 8px;
    }
</style>
