// WebUINew/src/pages/share.svelte
<script>
  import { onMount } from "svelte";
  import msgbox from "../UI/msgbox.js";
  import Button from "../UI/button.svelte";
  import ViewShare from "./viewshare.svelte";
  import entity from "../entities.js";
  import Fa from "svelte-fa";
import icons from "../icons.js";

  export let active = false;

  let shares = [];
  let selectedshare;
  let findshare = "";
  let sortcol = "Name";
  let sortAsc = true;
  let sharefilter;
  let draggable = false;

  $: sharefilter = window.FILTER(shares, findshare, sortcol, sortAsc);

  onMount(() => {
    refresh();
  });

  function sorticon(name, sc, sa) {
    if (sc === name) {
      if (sa === true) return icons.faSortAlphaDown;
      return icons.faSortAlphaDownAlt;
    }
    return "";
  }

  function refresh() {
    window.GET("api/getshares", function(data) {
      data.forEach((o, i) => (o.id = i));
      shares = data;
    });
  }

  function addshare() {
    var s = new entity.Share();
    // console.log(s);
    view(s, true);
  }

  function pause(share) {
    window.GET("api/share.pauseresume?" + share.Name + "&true", function() {
      refresh();
    });
  }

  function resume(share) {
    window.GET("api/share.pauseresume?" + share.Name + "&false", function() {
      refresh();
    });
  }

  function unshare(share, index) {
    msgbox.OkCancel(
      "Do you want to remove this share?",
      "Remove?",
      inputValue => {
        if (inputValue !== "") {
          window.GET("api/share.remove?" + share.Name, function() {
            refresh();
          });
        }
      }
    );
  }

  function sort(col) {
    if (col !== sortcol) {
      sortAsc = true;
      sortcol = col;
    } else sortAsc = !sortAsc;
  }

  function view(share, isnew) {
    var n = document.createElement("div");
    var e = document.body.appendChild(n);
    var ct = new ViewShare({
      target: n,
      props: { node: n, share, isnew }
    });
    ct.$on("close", e => refresh());
    ct.show = true;
  }
</script>

<style>
  .al {
    text-decoration: underline;
    cursor: pointer;
    margin-right: 8px;
  }
</style>

<svelte:options accessors={true} />

{#if active}
  <div class="tab-content">
    <h2>
      <Fa icon={icons.faFolderOpen} />
      Shares on this machine
    </h2>
    If you have a folder on this machine you want others to connect to, add that
    folder below.
    <br />
    <br />
    <Button on:click={addshare}>
      <Fa icon={icons.faPlus} />
      Add
    </Button>
    {#if shares.length > 0}
      <span>
        <label>
          <Fa icon={icons.faFilter} />
          Filter :
        </label>
        <input
          type="text"
          bind:value={findshare}
          placeholder="Type here to filter the grid" />
        <button on:click={() => (findshare = '')}>X</button>
        <label style="margin-left:5px;">Count = {sharefilter.length}</label>
      </span>
      <div class="cssTbl">
        <table>
          <tr>
            <th>
              <label on:click={() => sort('Name')}>
                Name
                <Fa icon={sorticon('Name', sortcol, sortAsc)} />
              </label>
            </th>
            <th>
              <label on:click={() => sort('Path')}>
                Path
                <Fa icon={sorticon('Path', sortcol, sortAsc)} />
              </label>
            </th>
            <th>
              <label>Actions</label>
            </th>
          </tr>
          {#each sharefilter as s, i (s.id)}
            <tr>
              <td>
                <label>
                  <label on:click={() => view(s, false)}>{s.Name}</label>
                </label>
              </td>
              <td>
                <label>{s.Path}</label>
              </td>
              <td>
                <label>
                  <label class="al" on:click={() => pause(s)}>
                    <Fa icon={icons.faPause} />
                    Pause
                  </label>
                </label>
                <label>
                  <label class="al" on:click={() => resume(s)}>
                    <Fa icon={icons.faPlay} />
                    Resume
                  </label>
                </label>
                <label>
                  <label class="al" on:click={() => unshare(s, i)}>
                    <Fa icon={icons.faTimes} />
                    Un-share
                  </label>
                </label>
              </td>
            </tr>
          {/each}
        </table>
      </div>
    {/if}
  </div>
{/if}

// WebUI/src/Vue/share.vue
<template>
	<div>
		<button class="actionbutton" @click="addshare"><span class="gi gi-plus" style="margin-right:10px;"></span>Add</button>
		<span v-if="sharefilter.length>0">
			<label><span class="gi gi-filter"></span>Filter :</label>
			<input type="text" v-model="findshare" placeholder="Type here to filter the grid">
			<button @click="findshare=''">X</button>
			<label style="margin-left:5px;">Count = {{sharefilter.length}}</label>
		</span>
		<div class="cssTbl">
			<table v-if="sharefilter.length>0">
				<tr>
					<th><a @click="sort('Name')">Name<span :class="sorticon('Name')"></span></a></th>
					<th><a @click="sort('Path')">Path<span :class="sorticon('Path')"></span></a></th>
					<th><a>Actions</a></th>
				</tr>
				<tr v-for="(s,i) in sharefilter">
					<td><label><a @click="view(s)">{{s.Name}}</a></label></td>
					<td>
						<label>{{s.Path}}</label>
					</td>
					<td>
						<label><a class="al" @click="pause(s)"><span class="gi gi-pause"></span>Pause</a></label>
						<label><a class="al" @click="resume(s)"><span class="gi gi-play"></span>Resume</a></label>
						<label><a class="al" @click="unshare(s,i)"><span class="gi gi-remove"></span>Un-share</a></label>
					</td>
				</tr>
			</table>
		</div>
		<viewshare :share="selectedshare" @refresh="refresh" :draggable="draggable"></viewshare>
	</div>
</template>

<script>
	import addshare from './viewshare.vue'
	export default {
		data() {
			return {
				selectedshare: {},
				findshare: '',
				sortcol: 'Name',
				sortAsc: true
			}
		},
		components: {
			'viewshare': addshare
		},
		props: ['shares'],
		methods: {
			sorticon(name) {
				if (this.sortcol === name) {
					if (this.sortAsc === true)
						return 's gi gi-sort-by-alphabet';
					return 's gi gi-sort-by-alphabet-alt';
				}
				return '';
			},
			refresh() {
				this.$emit("refresh");
			},
			addshare() {
				this.selectedshare = new Share();
				this.$modal.show('AddShareModal');
			},
			pause(share) {
				var that = this;
				$.get2("api/share.pauseresume?" + share.Name + "&true", function() {
					that.$emit("refresh");
				});
			},
			resume(share) {
				var that = this;
				$.get2("api/share.pauseresume?" + share.Name + "&false", function() {
					that.$emit("refresh");
				});
			},
			unshare(share, index) {
				var that = this;
				swal({
					title: "Remove?",
					text: "Do you want to remove this share?",
					showCancelButton: true,
					closeOnConfirm: true,
					cancelButtonText: 'Cancel',
					animation: "slide-from-top"
				}, function(inputValue) {
					if (inputValue === false) return false;
					if (inputValue !== "") {
						$.get2("api/share.remove?" + share.Name, function() {
							that.$emit("refresh");
						});
					}
				});
			},
			sort(col) {
				if (col !== this.sortcol) {
					this.sortAsc = true;
					this.sortcol = col;
				} else
					this.sortAsc = !this.sortAsc;
			},
			view(share) {
				this.selectedshare = share;
				this.$modal.show("AddShareModal")
			}
		},
		computed: {
			sharefilter() {
				return $.filter(this.shares, this.findshare, this.sortcol, this.sortAsc);
			},
            draggable(){
                return window.draggable;
            }
		}
	}
</script>

<style>
	.al {
		text-decoration: underline;
		cursor: pointer;
		margin-right: 8px;
	}
	.s {
		margin-left: 8px;
	}
</style>
